apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wow-backend
resources:
  - namespace.yaml
  - configmap.yaml
  - migrations-configmap.yaml
  - cloudnativepg-cluster.yaml
  - token-cleanup-cronjob.yaml
  - backend-deployment.yaml
  - backend-service.yaml
